id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Close "Need More Info" Issues
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isOpen
      - isIssue
      - hasLabel:
          label: Needs More Info
      - noActivitySince:
          days: 10
      actions:
      - closeIssue
      - addReply:
          reply: "Closing this issue as we've seen no reply to the request for more information. If you are able to get the requested information, please add it to the issue and we will retriage it. "
    eventResponderTasks:
    - if:
      - payloadType: Pull_Request
      - isPullRequest
      - labelAdded:
          label: auto-merge
      - and:
        - activitySenderHasPermission:
            permission: Admin
        - isActivitySender:
            user: dotnet-bot
            issueAuthor: False
      then:
      - approvePullRequest:
          comment: Auto-approve
      description: Auto-approve auto-merge PRs
    - if:
      - payloadType: Pull_Request
      - isPullRequest
      - isAction:
          action: Opened
      - not:
          bodyContains:
            pattern: Updates sdk.version
            isRegex: False
      - or:
        - isActivitySender:
            user: dotnet-maestro[bot]
            issueAuthor: False
        - isActivitySender:
            user: dotnet-maestro
            issueAuthor: False
      then:
      - approvePullRequest:
          comment: Auto-approve
      description: Auto-approve maestro PRs
    - if:
      - payloadType: Pull_Request
      - isPullRequest
      - targetsBranch:
          branch: main
      - and:
        - isAction:
            action: Closed
        - isMerged
      then:
      - addMilestone:
          milestone: Next
      description: Milestone tracking
    - if:
      - payloadType: Pull_Request
      - isPullRequest
      - isActivitySender:
          user: dotnet-bot
          issueAuthor: False
      - titleContains:
          pattern: Localized file check-in
          isRegex: False
      - isAction:
          action: Opened
      then:
      - addLabel:
          label: auto-merge
      description: Auto-approve OneLoc PRs
    - if:
      - payloadType: Issue_Comment
      - isIssue
      - isOpen
      - hasLabel:
          label: Needs More Info
      then:
      - removeLabel:
          label: Needs More Info
      description: Remove "Need More Info" on comment
    - if:
      - payloadType: Pull_Request
      - isPullRequest
      - isAction:
          action: Opened
      - and:
        - not:
            activitySenderHasPermission:
              permission: Admin
        - not:
            activitySenderHasPermission:
              permission: Write
        - not:
            isActivitySender:
              user: github-actions[bot]
              issueAuthor: False
        - not:
            isActivitySender:
              user: dotnet-maestro[bot]
              issueAuthor: False
        - not:
            isActivitySender:
              user: dotnet-maestro-bot[bot]
              issueAuthor: False
        - not:
            isActivitySender:
              user: dotnet-maestro-bot
              issueAuthor: False
        - not:
            isActivitySender:
              user: dotnet-maestro
              issueAuthor: False
        - not:
            isActivitySender:
              user: github-actions
              issueAuthor: False
      then:
      - addLabel:
          label: Community
      description: Label Community Pull Requests
onFailure: 
onSuccess: 
