# Branches that trigger a build on commit
trigger:
- main
- feature/*
- release/*

# Branches that trigger builds on PR
pr:
- main
- feature/*
- release/*

jobs:

- job: Format
  pool:
    vmImage: 'windows-latest'
  strategy:
    maxParallel: 8
    matrix:
      format:
        _repo: "https://github.com/dotnet/format"
        _repoName: "dotnet/format"
        _targetSolution: "format.sln"
        _branchName: "main"
        _sha: "c3b6ef4e4a480cae887bbf47fd674bfab380ef4e"
        _useParentSdk: 0
      roslyn:
        _repo: "https://github.com/dotnet/roslyn"
        _repoName: "dotnet/roslyn"
        _targetSolution: "Compilers.slnf"
        _branchName: "main"
        _sha: "a3bb37003aeccad012a6e7dd220977599e8b8e65"
        _useParentSdk: 0
      sdk:
        _repo: "https://github.com/dotnet/sdk"
        _repoName: "dotnet/sdk"
        _targetSolution: "sdk.sln"
        _branchName: "main"
        _sha: "be25db95c376bffd508a023399ddd34392fe6458"
        _useParentSdk: 0
      project-system:
        _repo: "https://github.com/dotnet/project-system"
        _repoName: "dotnet/project-system"
        _targetSolution: "ProjectSystem.sln"
        _branchName: "main"
        _sha: "e660d54d6b3198751bd0502fe270e1657f32a913"
        _useParentSdk: 1
      msbuild:
        _repo: "https://github.com/dotnet/msbuild"
        _repoName: "dotnet/msbuild"
        _targetSolution: "MSBuild.sln"
        _branchName: "main"
        _sha: "f4fa6bde775a3f7cbb2bb90a349ee5fc759114f3"
        _useParentSdk: 0
      aspnetcore:
        _repo: "https://github.com/dotnet/aspnetcore"
        _repoName: "dotnet/aspnetcore"
        _targetSolution: "AspNetCore.sln"
        _branchName: "main"
        _sha: "d765d7ba4871a8c2cb38d4134553d3be9a7370d7"
        _useParentSdk: 0
      efcore:
        _repo: "https://github.com/dotnet/efcore"
        _repoName: "dotnet/efcore"
        _targetSolution: "All.sln"
        _branchName: "main"
        _sha: "1b2ff365399ab6736a9ea4c98ab1b60acda5d917"
        _useParentSdk: 0
      razor-tooling:
        _repo: "https://github.com/dotnet/razor"
        _repoName: "dotnet/razor"
        _targetSolution: "Razor.sln"
        _branchName: "main"
        _sha: "ecb4b595e3322a18c240f50a763868540f51eaaa"
        _useParentSdk: 0
  timeoutInMinutes: 60
  steps:
    - script: eng\integration-test.cmd -repo '$(_repo)' -branchName '$(_branchName)' -sha '$(_sha)' -targetSolution '$(_targetSolution)' -useParentSdk $(_useParentSdk) -testPath '$(Agent.TempDirectory)\temp' -stage 'prepare'
      displayName: Prepare $(_repoName) for formatting

    - script: eng\integration-test.cmd -repo '$(_repo)' -branchName '$(_branchName)' -sha '$(_sha)' -targetSolution '$(_targetSolution)' -useParentSdk $(_useParentSdk) -testPath '$(Agent.TempDirectory)\temp' -stage 'format-workspace'
      displayName: Run dotnet-format on $(_repoName) $(_targetSolution)

    - script: eng\integration-test.cmd -repo '$(_repo)' -branchName '$(_branchName)' -sha '$(_sha)' -targetSolution '$(_targetSolution)' -useParentSdk $(_useParentSdk) -testPath '$(Agent.TempDirectory)\temp' -stage 'format-folder'
      displayName: Run dotnet-format on $(_repoName) repo folder
