# Branches that trigger a build on commit
trigger:
- master
- feature/*

# Branches that trigger builds on PR
pr:
- master
- feature/*

jobs:

- job: Format
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    maxParallel: 8
    matrix:
      format:
        _repo: "https://github.com/dotnet/format"
        _repoName: "dotnet/format"
        _sha: "e276d7f718092300f2e5317cc616bf330b272456"
      roslyn:
        _repo: "https://github.com/dotnet/roslyn"
        _repoName: "dotnet/roslyn"
        _sha: "b4973cd3df292e4de8ed9a8fb3dd18200b77fead"
      sdk:
        _repo: "https://github.com/dotnet/sdk"
        _repoName: "dotnet/sdk"
        _sha: "7b21f6103dd96b6b78beff24cdff9a10418c032b"
      project-system:
        _repo: "https://github.com/dotnet/project-system"
        _repoName: "dotnet/project-system"
        _sha: "363cb401c859fff9bcff1d253cc167b76a538713"
      msbuild:
        _repo: "https://github.com/Microsoft/msbuild"
        _repoName: "Microsoft/msbuild"
        _sha: "26f6d1d87700faa8b38d215dbde5968e6b8381f6"
      blazor:
        _repo: "https://github.com/aspnet/blazor"
        _repoName: "aspnet/blazor"
        _sha: "cc449601d638ffaab58ae9487f0fd010bb178a12"
      efcore:
        _repo: "https://github.com/dotnet/efcore"
        _repoName: "dotnet/efcore"
        _sha: "ef6af2d3def2ce50277809fa65c9f692d14741f6"
      ef6:
        _repo: "https://github.com/dotnet/ef6"
        _repoName: "dotnet/ef6"
        _sha: "d38aef7a548019c6769c65e3a0b495b8f80f75a9"
  timeoutInMinutes: 20
  steps:
    - script: eng\integration-test.cmd -repo '$(_repo)' -sha '$(_sha)' -testPath '$(Build.SourcesDirectory)\temp' -stage 'prepare'
      displayName: Prepare $(_repoName) for formatting

    - script: eng\integration-test.cmd -repo '$(_repo)' -sha '$(_sha)' -testPath '$(Build.SourcesDirectory)\temp' -stage 'format-workspace'
      displayName: Run dotnet-format on $(_repoName) solution files

    - script: eng\integration-test.cmd -repo '$(_repo)' -sha '$(_sha)' -testPath '$(Build.SourcesDirectory)\temp' -stage 'format-folder'
      displayName: Run dotnet-format on $(_repoName) repo folder