# Branches that trigger a build on commit
trigger:
- master

# Branches that trigger builds on PR
pr:
- master

jobs:

- job: Windows
  pool:
    name: NetCorePublic-Int-Pool
    queue: buildpool.windows.10.amd64.vs2017.open
  strategy:
    maxParallel: 4
  timeoutInMinutes: 120
  steps:
    - script: eng\integration-test.cmd -logPath '$(Build.SourcesDirectory)\artifacts\log\integration' -testPath '$(Build.SourcesDirectory)\temp'
      displayName: Run Integration Tests
    - task: PublishBuildArtifacts@1
      displayName: Publish Integration Test Logs
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\log\integration'
        ArtifactName: 'IntegrationTests'
      continueOnError: true
      condition: not(succeeded())
